core/urls.py
from django.urls import path
from .views import HomeView, SerieView, EpisodeView, SeasonView, MovieView, GenresView, SeriesListView, MoviesListView, TranslatorView

app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('serie/<slug>/', SerieView.as_view(), name='serie'),
    path('movie/<slug>/', MovieView.as_view(), name='movie'),
    path('genres/<slug:slug>/', GenresView.as_view(), name='genres'),
    path('series-list/', SeriesListView.as_view(), name='series_list'),
    path('translator/<slug:slug>/', TranslatorView.as_view(), name='translator'),
    path('movies-list/', MoviesListView.as_view(), name='movies_list'),
    path('serie/<slug:serie_slug>/<slug:slug>/', SeasonView.as_view(), name='season'),
    path('serie/<slug:serie_slug>/<slug:season_slug>/<slug:slug>/', EpisodeView.as_view(), name='episode')
]

vietsubcartoons/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.shortcuts import reverse
from django_extensions.db.fields import AutoSlugField

TYPE_CHOICES = (
    ('S', 'Phim bộ'),
    ('M', 'Phim lẻ')
)
STATUS_CHOICES = (
    ('HT', 'Hoàn thành'),
    ('DC', 'Đang sub'),
    ('DR', 'Drop')
)


class Category(models.Model):
    name = models.CharField(max_length=20)
    slug = AutoSlugField(populate_from=['name', ])

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("core:genres", kwargs={
            'slug': self.slug
        })


class Translator(models.Model):
    name = models.CharField(max_length=50, default='')
    fb = models.CharField(max_length=200, default='')
    slug = AutoSlugField(populate_from=['name', ])

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("core:translator", kwargs={
            'slug': self.slug
        })


class Film(models.Model):
    title = models.CharField(max_length=100, default='', blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)
    description = models.TextField()
    views = models.IntegerField(default=0)
    status = models.CharField(choices=STATUS_CHOICES, max_length=2)
    typ = models.CharField(choices=TYPE_CHOICES, max_length=2)
    poster_url = models.CharField(max_length=255, blank=True, null=True)
    banner_url = models.CharField(max_length=255, blank=True, null=True)
    created_by = models.CharField(max_length=100, blank=True, null=True)
    imdb = models.FloatField(default=0)
    publish_date = models.DateField(auto_now=True)
    slug = AutoSlugField(populate_from=['title', ])
    category = models.ManyToManyField(Category)

    def __str__(self):
        return self.title

    def get_type(self):
        pass


class Serie(Film):

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:serie", kwargs={
            'slug': self.slug
        })

    def get_type(self):
        return "Serie"


class Movie(Film):
    url_fb = models.CharField(max_length=1000, blank=True, null=True)
    url_gd = models.CharField(max_length=1000, blank=True, null=True)
    trailer = models.CharField(max_length=255)
    translator = models.ManyToManyField(Translator)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:movie", kwargs={
            'slug': self.slug
        })

    def get_type(self):
        return "Movie"


class SerieSeason(models.Model):
    season_number = models.IntegerField(blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)
    poster_url = models.CharField(max_length=255, blank=True, null=True)
    banner_url = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=2)
    episode_total = models.IntegerField()
    serie = models.ForeignKey(Serie, on_delete=models.CASCADE)
    slug = models.SlugField()
    imdb = models.FloatField(default=0)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.serie.title + ' Mùa ' + str(self.season_number)

    def get_absolute_url(self):
        return reverse("core:season", kwargs={
            'serie_slug': self.serie.slug,
            'slug': self.slug
        })


class Episode(models.Model):
    ep_number = models.IntegerField(blank=True, null=True)
    title = models.CharField(max_length=200)
    publish_date = models.DateField(auto_now=True)
    url_fb = models.CharField(max_length=1000, blank=True, null=True)
    url_gd = models.CharField(max_length=1000, blank=True, null=True)
    views = models.IntegerField(default=0)
    season = models.ForeignKey(SerieSeason, on_delete=models.CASCADE)
    slug = AutoSlugField(populate_from=['title', ])
    thumbnail_url = models.CharField(max_length=200)
    imdb = models.FloatField(default=0)
    translator = models.ManyToManyField(Translator)

    def __str__(self):
        return str(self.season) + ' Tập ' + str(self.ep_number)

    def get_absolute_url(self):
        return reverse("core:episode", kwargs={
            'serie_slug': self.season.serie.slug,
            'season_slug': self.season.slug,
            'slug': self.slug
        })

templates/film_list.html
{% extends "base.html" %}
{% load static%}
{% load util %}
{% block content%}
<div class="general-agileits-w3l">
	<div class="w3l-medile-movies-grids">

		<!-- /movie-browse-agile -->

		<div class="movie-browse-agile">
			<!--/browse-agile-w3ls -->
			<div class="browse-agile-w3ls general-w3ls">
				<div class="tittle-head">
					<h4 class="latest-text">{{ object_list.0.get_typ_display }} </h4>
					<div class="container">
						<div class="agileits-single-top">
							<ol class="breadcrumb">
								<li><a href="/">Home</a></li>
								<li class="active">{{ object_list.0.get_typ_display }}</li>
							</ol>
						</div>
					</div>
				</div>
				<div class="container">
					<div class="browse-inner">
						{% for serie in object_list %}
						<div class="col-md-2 w3l-movie-gride-agile">
							<a href="{{ serie.get_absolute_url }}" class="hvr-shutter-out-horizontal"><img
									src="{{ serie.poster_url }}" title="{{ serie.title }}" class="img-responsive"
									alt=" " />
								<div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
							</a>
							<div class="mid-1 agileits_w3layouts_mid_1_home">
								<div class="w3l-movie-text">
									<h6><a href="{{ serie.get_absolute_url }}">{{ serie.title }}</a></h6>
								</div>
								<div class="mid-2 agile_mid_2_home">
									<p>{{ serie.year }}</p>
									<div class="block-stars">
									</div>
									{% for cate in serie.category.all %}
									<a href="{{ cate.get_absolute_url }}" class="badge badge-pill badge-danger">{{ cate }}</a>
									{% endfor %}
									<div class="clearfix"></div>
								</div>
							</div>
							<div class="nhan">
								<p class="status">{{ serie.get_status_display }}</p>
							</div>
						</div>
						{% endfor %}
						<div class="clearfix"> </div>
					</div>
				</div>
			</div>
			<!--//browse-agile-w3ls -->
			{% if is_paginated %}
			<div class="blog-pagenat-wthree">
				<ul>
					{% if page_obj.has_previous %}
					<li><a class="frist" href="?page=1"><<</a></li>
					<li><a href="?page={{ page_obj.previous_page_number }}"><</a></li>
					{% endif %}
					<li><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
					{% if page_obj.has_next %}
					<li><a href="?page={{ page_obj.next_page_number }}">></a></li>
					<li><a class="last" href="?page={{ page_obj.paginator.num_pages }}">>></a></li>
					{% endif %}
				</ul>
				<span class="text-center">
					{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
				</span>
			</div>
			
			{% endif %}
		</div>
		<!-- //movie-browse-agile -->
	</div>
	<!-- //w3l-medile-movies-grids -->
</div>
{% endblock content%}

templates/footer.html
<!-- footer -->
	<div class="footer">
		<div class="container">
			<div class="w3ls_footer_grid">
				<div class="col-md-6 w3ls_footer_grid_left">
					<small>Trang web này không chịu trách nhiệm đối với bất kỳ nội dung nào được đăng tải trong trang web này.
						Mọi nội dung đều được sưu tầm và nhúng vào website tương tự như công cụ tìm kiếm Google.
						Disclaimer: This site does not store any files on its server. All contents are provided by non-affiliated third parties.</small>
				</div>
				<div class="col-md-6 w3ls_footer_grid_right">
					<a href="index.html">
						<h2>Vietsub<span>Cartoons</span></h2>
					</a>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="col-md-5 w3ls_footer_grid1_left">
				<p>&copy; 2020 Vietsub Cartoons. All rights reserved </p>
			</div>
			<div class="col-md-7 w3ls_footer_grid1_right">
				<ul>
					<li>
						<a href="/movies-list/">Movies</a>
					</li>
					{% for genres in genres_list %}
					<li><a href="{{ genres.get_absolute_url }}">{{ genres.name }}</a></li>
					{% endfor %}
					<li>
						<a href="https://facebook.com/vietsubcartoons/">Contact Us</a>
					</li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!-- //footer -->

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- banner -->
<div id="slidey" style="display:none;">
	<ul>
		{% for item in serie_list %}
		<li><img src="{{ item.banner_url }}" alt=" ">
			<p class='title'>{{ item.title }}</p>
			<p class='description'> {{ item.description }}</p>
		</li>
		{% endfor %}
	</ul>
</div>
<script src="{% static 'js/jquery.slidey.js' %}"></script>
<script src="{% static 'js/jquery.dotdotdot.min.js' %}"></script>
<script type="text/javascript">
	$("#slidey").slidey({
		interval: 8000,
		listCount: 5,
		autoplay: false,
		showList: true
	});
	$(".slidey-list-description").dotdotdot();
</script>
<!-- //banner -->
<!-- banner-bottom -->
<div class="banner-bottom">
	<h4 class="latest-text w3_latest_text">Tập mới cập nhật</h4>
	<div class="container">
		<div class="w3_agile_banner_bottom_grid">
			<div id="owl-demo" class="owl-carousel owl-theme">
				{% for item in episode_list %}
				<div class="item">
					<div class="w3l-movie-gride-agile w3l-movie-gride-agile1">
						<a href="{{ item.get_absolute_url }}" class="hvr-shutter-out-horizontal"><img
								src="{{ item.thumbnail_url }}" title="{{ item }}" class="img-responsive" alt=" " />
							<div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
						</a>
						<div class="mid-1 agileits_w3layouts_mid_1_home">
							<div class="w3l-movie-text">
								<h6><a href="{{ item.get_absolute_url }}">{{ item }}</a></h6>
							</div>
							<div class="mid-2 agile_mid_2_home">
								<p>{{ item.publish_date }}</p>
								<div class="block-stars">
								</div>
								<p style="float:right; color:red;">{{ item.views }} Views</p>
								<div class="clearfix"></div>
							</div>
						</div>
						<div class="ribben">
							<p>{{ season }} Mùa</p>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
<!-- //banner-bottom -->

<!-- general -->
<div class="general">
	<h4 class="latest-text w3_latest_text">Phim bộ mới</h4>
	<div class="container">
		<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
			<div id="myTabContent" class="tab-content">
				<div role="tabpanel" class="tab-pane fade active in" id="home" aria-labelledby="home-tab">
					<div class="w3_agile_featured_movies">
						{% for item in object_list %}
						<div class="col-md-2 w3l-movie-gride-agile">
							<a href="{{ item.get_absolute_url }}" class="hvr-shutter-out-horizontal"><img
									src="{{ item.poster_url }}" title="{{ item.title }}" class="img-responsive"
									alt=" " />
								<div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
							</a>
							<div class="mid-1 agileits_w3layouts_mid_1_home">
								<div class="w3l-movie-text">
									<h6><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></h6>
								</div>
								<div class="mid-2 agile_mid_2_home">
									<p>{{ item.year }}</p>
									<div class="block-stars">

									</div>
									{% for cate in item.category.all %}
									<a href="genres/{{ cate.slug }}"
										class="badge badge-pill badge-danger">{{ cate }}</a>
									{% endfor %}
									<div class="clearfix"></div>
								</div>
							</div>
							<div class="nhan">
								<p class="status">{{ item.get_status_display }}</p>
							</div>
						</div>
						{% endfor %}
						<div class="clearfix"> </div>
					</div>
				</div>
			</div>
		</div>
		<button class="see-more"><a href="/series-list">Xem thêm</a></button>
	</div>
</div>
<!-- //general -->
<!-- Latest-tv-series -->
<div class="Latest-tv-series">
	<h4 class="latest-text w3_latest_text w3_home_popular">Phim lẻ hot</h4>
	<div class="container">
		<section class="slider">
			<div class="flexslider">
				<ul class="slides">
					{% for topmovie in top_movie_list %}
					<li>
						<div class="agile_tv_series_grid">
							<div class="col-md-6 agile_tv_series_grid_left">
								<div class="w3ls_market_video_grid1">
									<img src="{{ topmovie.banner_url }}" alt=" " class="img-responsive" />
									<a class="w3_play_icon" href="#small-dialog{{ forloop.counter }}">
										<span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span>
									</a>
								</div>
							</div>
							<div class="col-md-6 agile_tv_series_grid_right">
								<p class="fexi_header">{{ topmovie.title }}</p>
								<p class="fexi_header_para"><span class="conjuring_w3">Story Line<label></label></span>
									{{ topmovie.description }}</p>
								<p class="fexi_header_para"><span>Date of Release<label></label></span>
									{{ topmovie.year }} </p>
								<p class="fexi_header_para">
									<span>Genres<label></label> </span>
									{% for cate in topmovie.category.all %}
									<a href="genres/{{ cate.slug }}">{{ cate }}</a>
									{% endfor %}
								</p>
								<p class="fexi_header_para fexi_header_para1"><span>Star Rating<label></label></span>
									{{ topmovie.imdb }}
								</p>
							</div>
							<div class="clearfix"> </div>
							<div class="agileinfo_flexislider_grids">
								{% for movie in top_movie_list %}
								<div class="col-md-2 w3l-movie-gride-agile">
									<a href="{{ movie.get_absolute_url }}" class="hvr-shutter-out-horizontal"><img
											src="{{ movie.poster_url }}" title="{{ movie.title }}"
											class="img-responsive" alt=" " />
										<div class="w3l-action-icon"><i class="fa fa-play-circle"
												aria-hidden="true"></i></div>
									</a>
									<div class="mid-1 agileits_w3layouts_mid_1_home">
										<div class="w3l-movie-text">
											<h6><a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a></h6>
										</div>
										<div class="mid-2 agile_mid_2_home">
											<p>{{ movie.year }}</p>
											<div class="block-stars">

											</div>
											{% for cate in movie.category.all %}
											<a href="genres/{{ cate.slug }}"
												class="badge badge-pill badge-danger">{{ cate }}</a>
											{% endfor %}
											<div class="clearfix"></div>
										</div>
									</div>
									<div class="ribben">
										<p>NEW</p>
									</div>
								</div>
								{% endfor %}
								<div class="clearfix"> </div>
							</div>
						</div>
					</li>
					<div id="small-dialog{{ forloop.counter }}" class="mfp-hide">
						<iframe src="{{ topmovie.trailer }}"></iframe>
					</div>
					{% endfor %}
				</ul>
			</div>
			<button class="see-more"><a href="/movies-list">Xem thêm</a></button>
		</section>
		<!-- flexSlider -->
		<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" property="" />
		<script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
		<script type="text/javascript">
			$(window).load(function () {
				$('.flexslider').flexslider({
					animation: "slide",
					start: function (slider) {
						$('body').removeClass('loading');
					}
				});
			});
		</script>
		<!-- //flexSlider -->
	</div>
</div>
<!-- pop-up-box -->
<script src="{% static 'js/jquery.magnific-popup.js' %}" type="text/javascript"></script>
<!--//pop-up-box -->


<script>
	$(document).ready(function () {
		$('.w3_play_icon,.w3_play_icon1,.w3_play_icon2').magnificPopup({
			type: 'inline',
			fixedContentPos: false,
			fixedBgPos: true,
			overflowY: 'auto',
			closeBtnInside: true,
			preloader: false,
			midClick: true,
			removalDelay: 300,
			mainClass: 'my-mfp-zoom-in'
		});

	});
</script>
<!-- //Latest-tv-series -->

{% endblock content %}

templates/list.html
{% extends "base.html" %}
{% load static%}
{% load util %}
{% block content%}
<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
    <div class="tittle-head">
        <h4 class="latest-text">Translator </h4>
        <div class="container">
            <div class="agileits-single-top">
                <ol class="breadcrumb">
                    <li><a href="/">Home</a></li>
                    <li class="active">Translator / {{ object }}</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
            <ul id="myTab" class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#serie" id="serie-tab" role="tab" data-toggle="tab" aria-controls="serie" aria-expanded="true">PHIM BỘ</a></li>
                <li role="presentation" class=""><a href="#movie" role="tab" id="movie-tab" data-toggle="tab" aria-controls="movie" aria-expanded="false">PHIM LẺ</a></li>
            </ul>
            <div id="myTabContent" class="tab-content">
                <div role="tabpanel" class="tab-pane fade active in" id="serie" aria-labelledby="serie-tab">
                    <div class="agile-news-table">
                        <div class="w3ls-news-result">
                        </div>
                        <table id="table-breakpoint">
                            <thead>
                              <tr>
                                <th>No.</th>
                                <th>Name</th>
                                <th>Year</th>
                                <th>Status</th>
                                <th>Views</th>
                                <th>Genre</th>
                                <th>Rating</th>
                              </tr>
                            </thead>
                            <tbody>
                                {% for item in episode_list %}
                              <tr>
                                <td data-th="No."><span class="bt-content">{{ forloop.counter }}</span></td>
                                <td class="w3-list-img" data-th="Movie Name"><span class="bt-content"><a href="{{ item.get_absolute_url }}"><img class="small-poster" src="{{ item.season.poster_url }}" alt="{{ item.title}}"> <span>{{ item.title}}</span></a></span></td>
                                <td data-th="Year"><span class="bt-content">{{ item.season.year}}</span></td>
                                <td data-th="Status"><span class="bt-content">{{ item.season.get_status_display }}</span></td>
                                <td class="w3-list-info" data-th="Country"><span class="bt-content">{{ item.views }}</span></td>
                                <td class="w3-list-info" data-th="Genre"><span class="bt-content">{% for cate in item.season.serie.category.all %}
									<a href="{{ cate.get_absolute_url }}" class="badge badge-pill badge-danger">{{ cate }}</a>
									{% endfor %}</span></td>
                                <td data-th="Rating"><span class="bt-content">{{ item.imdb }}</span></td>
                              </tr>
                              {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane fade" id="movie" aria-labelledby="movie-tab">
                    <div class="agile-news-table">
                        <div class="w3ls-news-result">
                        </div>
                        <table id="table-breakpoint1">
                            <thead>
                              <tr>
                                <th>No.</th>
                                <th>Name</th>
                                <th>Year</th>
                                <th>Status</th>
                                <th>Views</th>
                                <th>Genre</th>
                                <th>Rating</th>
                              </tr>
                            </thead>
                            <tbody>
                                {% for item in movie_list %}
                                <tr>
                                  <td data-th="No."><span class="bt-content">{{ forloop.counter }}</span></td>
                                  <td class="w3-list-img" data-th="Movie Name"><span class="bt-content"><a href="{{ item.get_absolute_url }}"><img class="small-poster" src="{{ item.poster_url}}" alt="{{ item.title}}"> <span>{{ item.title}}</span></a></span></td>
                                  <td data-th="Year"><span class="bt-content">{{ item.year}}</span></td>
                                  <td data-th="Status"><span class="bt-content">{{ item.get_status_display }}</span></td>
                                  <td class="w3-list-info" data-th="Country"><span class="bt-content">{{ item.views }}</span></td>
                                  <td class="w3-list-info" data-th="Genre"><span class="bt-content">{% for cate in item.category.all %}
                                      <a href="{{ cate.get_absolute_url }}" class="badge badge-pill badge-danger">{{ cate }}</a>
                                      {% endfor %}</span></td>
                                  <td data-th="Rating"><span class="bt-content">{{ item.imdb }}</span></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
    </div>
    </div>
</div>
{% endblock content %}

templates/movie.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="single-page-agile-main">
    <div class="container">
        <!-- /w3l-medile-movies-grids -->
        <div class="agileits-single-top">
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li>{{ object.title }}</li>
            </ol>
        </div>
        <div class="single-page-agile-info">
            <!-- /movie-browse-agile -->
            <div class="show-top-grids-w3lagile">
                <div class="col-sm-8 single-left">
                    <div class="song">
                        <div class="song-info">
                            <h3>{{ object.title }}</h3>
                        </div>
                    </div>
                    <div class="song-grid-right">
                        <div class="song-grid-right">
                            <div class="share">
                                <h5>Xem phim</h5>
    
                            </div>
                        </div>
                        <div class="clearfix"> </div>
    
                        <div class="all-season">
                            <div class="single-left" id="myDIV">
                                {% if object.url_fb %}
                                <div itemscope itemtype="https://schema.org/VideoObject">
                                    <meta itemprop="uploadDate"
                                        content="Sun Aug 16 2020 21:09:08 GMT+0700 (Giờ Đông Dương)" />
                                    <meta itemprop="name" content="Futurama Mùa 2 Tập 1" />
                                    <div style="position:relative; overflow:hidden; padding-bottom:56.25%"> <iframe
                                            src="https://cdn.jwplayer.com/players/{{ object.url_fb }}-4Kc0OEDF.html"
                                            frameborder="0" scrolling="auto" title="{{ object.title }}"
                                            style="position:absolute;" width="100%" height="100%" allowfullscreen></iframe>
                                    </div>
                                </div>
                                {% else %}
                                <iframe id="iFrame1" src="https://playhydrax.com/?v={{ object.url_gd }}" frameborder="0"
                                    scrolling="0" title="{{ object.title }}" allowfullscreen></iframe>
                                {% endif %}
                            </div>
                        </div>
                        <div class="share">
                            <h5>Thông tin về phim</h5>
                            <div class="single-right-grids">
                                <div class="col-md-4 single-right-grid-left ">
                                    <a href="{{ object.get_absolute_url }}"><img class="poster"
                                            src="{{ object.poster_url }}" alt="" /></a>
                                </div>
                                <div class="col-md-8 single-right-grid-right">
                                    <a href="{{ object.get_absolute_url }}" class="title"> {{ object.title }}</a>
                                    <p class="author"><strong>Năm: </strong><a href="#"
                                            class="author">{{ object.year }}</a></p>
                                    <p class="author"><strong>Trạng thái: </strong>{{ object.get_status_display }}</p>
                                    <p class="author"><strong>Thể loại: </strong>{% for cate in object.category.all %}
                                        <a href="{{ cate.get_absolute_url }}" >{{ cate }}, </a>
                                        {% endfor %}</p>
                                    <p class="views"><strong>Nội dung: </strong>{{ object.description }}</p>
                                </div>
                                <div class="clearfix"> </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-md-4 single-right">
                    <h3>Up Next</h3>
                    <div class="single-grid-right">
                        {% for movie in movie_list %}
                        <div class="single-right-grids">
                            <div class="col-md-4 single-right-grid-left">
                                <a href="{{ movie.get_absolute_url }}"><img src="{{ movie.poster_url }}" alt="" /></a>
                            </div>
                            <div class="col-md-8 single-right-grid-right">
                                <a href="{{ movie.get_absolute_url }}" class="title"> {{ movie.title }}</a>
                                <p class="author"><a href="#" class="author">{{ movie.year }}</a></p>
                                <p class="views">{{ movie.views }} views</p>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>



                <div class="clearfix"> </div>
            </div>
            <!-- //movie-browse-agile -->
            <!--body wrapper start-->
            <div class="w3_agile_banner_bottom_grid">
                <div id="owl-demo" class="owl-carousel owl-theme">
                    {% for serie in serie_list %}
                    <div class="item">
                        <div class="w3l-movie-gride-agile w3l-movie-gride-agile1">
                            <a href="{{ serie.get_absolute_url }}" class="hvr-shutter-out-horizontal"><img
                                    src="{{ serie.poster_url }}" title="{{ serie.title }}" class="img-responsive"
                                    alt=" " />
                                <div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
                            </a>
                            <div class="mid-1 agileits_w3layouts_mid_1_home">
                                <div class="w3l-movie-text">
                                    <h6><a href="{{ serie.get_absolute_url }}">{{ serie.title }}</a></h6>
                                </div>
                                <div class="mid-2 agile_mid_2_home">
                                    <p>{{ serie.year }}</p>
                                    <div class="block-stars">
                                        <ul class="w3l-ratings">
                                            <li><a href="#">{{ serie.get_category_display }}</a></li>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="ribben">
                                <p>NEW</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!--body wrapper end-->


            </div>
            <!-- //w3l-latest-movies-grids -->
        </div>
    </div>
    <!-- //w3l-medile-movies-grids -->

    {% endblock content %}